# Generated by Django 3.2.8 on 2021-10-20 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0002_auto_20211020_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='poll',
        ),
        migrations.AddField(
            model_name='election',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='election', to='auth.user'),
            preserve_default=False,
        ),
    ]
