# Generated by Django 3.2.8 on 2021-10-20 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20211020_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='poll',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='election', to='polls.poll'),
            preserve_default=False,
        ),
    ]
